language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
  fast_finish: true

before_install:
  # Disable XDebug speed up test execution.
  - phpenv config-rm xdebug.ini || return 0
  # Enable MongoDB extension
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
  # Install a polyfill for Mongo extension on PHP 7
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then travis_retry composer config "platform.ext-mongo" "1.6.16" && composer require alcaeus/mongo-php-adapter; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then travis_retry composer update; fi
  - composer info

script:
  - vendor/bin/phpunit --exclude-group=none

branches:
  only:
    - master

services:
  - mongodb
